name = "erdos_612_lean4web"
version = "0.1.0"
defaultTargets = ["Erdos612Lean4Web"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "Erdos612Lean4Web"
